import { relations, sql } from "drizzle-orm";
import {
  check,
  index,
  numeric,
  pgTable,
  smallint,
  timestamp,
  uuid,
} from "drizzle-orm/pg-core";

import { company } from "./company";
import { alert } from "./alert";

/** PROJECTION [MCP] — system output generated by project_consumption. */
export const projection = pgTable(
  "projection",
  {
    id: uuid("id").primaryKey().default(sql`gen_random_uuid()`),
    companyId: uuid("company_id")
      .notNull()
      .references(() => company.id, { onDelete: "cascade" }),
    year: smallint("year").notNull(),
    month: smallint("month").notNull(),
    forecastTemp: numeric("forecast_temp", { precision: 5, scale: 2 }).notNull(),
    /** unit depends on dominant vector */
    estimatedConsumption: numeric("estimated_consumption", {
      precision: 16,
      scale: 2,
    }).notNull(),
    /** $ */
    estimatedCost: numeric("estimated_cost", {
      precision: 16,
      scale: 2,
    }).notNull(),
    /** % vs. mild reference month */
    variationPct: numeric("variation_pct", { precision: 6, scale: 2 }),
    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (table) => [
    index("idx_projection_company").on(
      table.companyId,
      table.year,
      table.month,
    ),
    check("projection_year_check", sql`${table.year} BETWEEN 1990 AND 2100`),
    check("projection_month_check", sql`${table.month} BETWEEN 1 AND 12`),
  ],
);

export const projectionRelations = relations(projection, ({ one, many }) => ({
  company: one(company, {
    fields: [projection.companyId],
    references: [company.id],
  }),
  alerts: many(alert),
}));
